# config.yaml
karyotype: "karyotype.txt"
chromosomes_units: 100000

plots:
  - type: "heatmap"
    file: "gene.tsv"
    r0: "0.90r"
    r1: "0.95r"
    color: "purples-9-seq"
    min: 0
    max: 50
    orientation: "out"  # 可选参数

  - file: "gypsy.tsv"
    r0: "0.80r"
    r1: "0.85r"
    color: "blues-9-seq"
    min: 0
    max: 107

  - file: "copia.tsv"
    r0: "0.70r"
    r1: "0.75r"
    color: "bugn-9-seq"
    min: 0
    max: 98

links:
  file: "links.tsv"
  radius: "0.65r"
  bezier_radius: "0r"
  color: "vvlgrey"
  thickness: 2
